Portfolio desktop version with media queries
jash-debug/Portfolio-setup-and-mobile-first pull request #4
Opened 2022-08-25 14:45 UTC by jash-debug

Add classes and text to the html structure
Add media queries at the bottom of the CSS for desktop version
Add images 
Fix linter errors

2022-08-25 16:22 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @jash-debug, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 16:22 UTC, leonardodiasb commented on index.html
>                          <button type="submit" class="form__button poppins">Get In Touch</button>
- [ ] The Get In Touch button of the Figma template on the desktop version of the form is aligned in the center. Kindly reposition this button so the form can match with the Figma template.
 -Your design:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/61919617/186716319-ee6444e6-126e-497f-b525-c39661185fee.png">
-Figma template:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/61919617/186716398-3c9da0aa-ac38-4a26-a186-dc3d16e9af90.png">

2022-08-25 16:22 UTC, leonardodiasb commented on index.html
>          </div>
- [ ] Some project cards are not responsive and their images do not resize. This is causing the content of the project cards to be displayed outside of the card's boundaries and out of the screen on screen sizes close to the 768px transition. This is a bad visual design. Please review the sizing of elements inside the card so they can be responsive. 
 -Your design:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/61919617/186718232-6d776257-c962-4e5f-9a1f-55df8c8c2261.png">

2022-08-26 05:25 UTC, Ismailco approved these changes
### Hi @jash-debug, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 05:33 UTC, merged